// Lightweight "lazy" helpers for the gallery publish/edit dialog.
// No API keys required: auto-description is template-based, and translation
// uses the free MyMemory public endpoint (browser-side). Both degrade
// gracefully when a network call is unavailable.

export type GalleryLang = 'zh' | 'en' | 'ja';

export const LANG_LABELS: Record<GalleryLang, string> = {
  zh: '中文',
  en: 'English',
  ja: '日本語',
};

// Map our locale codes to MyMemory langpair codes.
const MM_CODE: Record<GalleryLang, string> = {
  zh: 'zh-CN',
  en: 'en',
  ja: 'ja',
};

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
export const titleKey = (l: GalleryLang) => `title${cap(l)}` as const;
export const descKey = (l: GalleryLang) => `description${cap(l)}` as const;

/** URL-safe slug from an arbitrary string (ASCII only). */
export function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

const hasCJK = (s: string) =>
  /[一-鿿぀-ヿ가-힯]/.test(s);

/**
 * Choose the slug source. Slugs must be ASCII, so we only consider fields
 * that are meant to hold Latin text:
 *   1) the English title, or
 *   2) a Japanese *romaji* title (Latin only — kana counts as CJK).
 * The Chinese title is intentionally NEVER used: typing pinyin in the
 * Chinese box (e.g. "shi ma") is Latin text and would otherwise produce a
 * junk slug like "shi-ma".
 * Returns '' when no valid Latin source exists (the caller leaves slug empty
 * and shows a hint instead of inventing junk).
 */
export function pickSlugSource(form: FormLike): string {
  const en = String(form.titleEn || '').trim();
  const ja = String(form.titleJa || '').trim();
  if (en && !hasCJK(en)) return en;
  if (ja && !hasCJK(ja)) return ja;
  return '';
}

export interface AutoSlugResult {
  slug: string;
  /** English title derived via translation (only when no Latin source existed). */
  enTitle?: string;
}

/**
 * Produce a slug, auto-translating a CJK-only title to English first.
 *   1) Use the English / romaji-Japanese title if it holds Latin text (sync).
 *   2) Else translate the Chinese title → English, slugify that.
 *   3) Else translate a pure-Japanese (kana/kanji) title → English.
 * Returns null only when there is no title at all or translation failed.
 */
export async function autoSlug(form: FormLike): Promise<AutoSlugResult | null> {
  const en = String(form.titleEn || '').trim();
  const ja = String(form.titleJa || '').trim();
  const zh = String(form.titleZh || '').trim();

  if (en && !hasCJK(en)) return { slug: slugify(en) };
  if (ja && !hasCJK(ja)) return { slug: slugify(ja) };

  if (zh) {
    const enTitle = await translateText(zh, 'zh', 'en');
    const s = slugify(enTitle || '');
    return s ? { slug: s, enTitle: enTitle ?? undefined } : null;
  }
  if (ja) {
    const enTitle = await translateText(ja, 'ja', 'en');
    const s = slugify(enTitle || '');
    return s ? { slug: s, enTitle: enTitle ?? undefined } : null;
  }
  return null;
}

interface AutoDescInput {
  cosplayer?: string;
  character?: string;
  series?: string;
  tags?: string[];
  imageCount?: number;
}

/**
 * Build a sensible, locale-specific description from the gallery's
 * structured fields — so an admin never has to write prose by hand.
 */
export function autoGenerateDescriptions(input: AutoDescInput): Record<
  'descriptionZh' | 'descriptionEn' | 'descriptionJa',
  string
> {
  const cos = input.cosplayer?.trim() || '匿名';
  const char = input.character?.trim();
  const series = input.series?.trim();
  const tags = (input.tags || []).filter(Boolean);
  const n = Math.max(0, input.imageCount || 0);
  const countPhrase = {
    zh: n > 0 ? `共 ${n} 张高清写真` : '精选 cosplay 写真',
    en: n > 0 ? `featuring ${n} high-resolution photos` : 'a curated cosplay set',
    ja: n > 0 ? `全${n}枚の高解像度画像` : '厳選されたコスプレ写真',
  };
  const tagsZh = tags.length ? `。标签：${tags.join('、')}` : '';
  const tagsEn = tags.length ? `. Tags: ${tags.join(', ')}` : '';
  const tagsJa = tags.length ? `。タグ：${tags.join('、')}` : '';

  // zh
  const zhWho = char && series ? `${series} 的 ${char}` : char || series || '角色';
  const zh = `【${zhWho}】${cos} 的精致 cosplay 图包，${countPhrase.zh}${tagsZh}。`;

  // en
  const enWho = [char, series].filter(Boolean).join(' from ');
  const en = `${cos}'s exquisite cosplay set${
    enWho ? ` of ${enWho}` : ''
  }, ${countPhrase.en}${tagsEn}.`;

  // ja
  const jaWho = char && series ? `${series}の${char}` : char || series || 'キャラクター';
  const ja = `${cos}による${jaWho}の精巧なコスプレ写真集、${countPhrase.ja}${tagsJa}。`;

  return { descriptionZh: zh, descriptionEn: en, descriptionJa: ja };
}

/** Translate a single string via the free MyMemory endpoint. */
export async function translateText(
  text: string,
  from: GalleryLang,
  to: GalleryLang,
  timeoutMs = 8000
): Promise<string | null> {
  const q = text.trim();
  if (!q || from === to) return null;
  if (q.length > 400) return null; // free tier caps request size
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const url =
      `https://api.mymemory.translated.net/get?q=${encodeURIComponent(
        q
      )}&langpair=${MM_CODE[from]}|${MM_CODE[to]}`;
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) return null;
    const data = await res.json();
    const t: unknown = data?.responseData?.translatedText;
    if (typeof t === 'string' && !t.startsWith('MYMEMORY WARNING')) {
      return t.trim();
    }
    return null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

type FormLike = Record<string, unknown>;

/**
 * Translate the title + description from `source` into the other two
 * locales. Returns a partial form patch. On a per-field failure the
 * source text is copied across as a fallback so the target is never
 * left empty.
 */
export async function translateGallery(
  form: FormLike,
  source: GalleryLang
): Promise<FormLike> {
  const targets = (['zh', 'en', 'ja'] as GalleryLang[]).filter(
    (l) => l !== source
  );
  const patch: FormLike = {};
  const jobs: Promise<void>[] = [];

  for (const field of ['title', 'description'] as const) {
    const srcKey = field === 'title' ? titleKey(source) : descKey(source);
    const srcVal = String(form[srcKey] || '').trim();
    if (!srcVal) continue;
    for (const tgt of targets) {
      const tgtKey = field === 'title' ? titleKey(tgt) : descKey(tgt);
      jobs.push(
        (async () => {
          const translated = await translateText(srcVal, source, tgt);
          patch[tgtKey] = translated ?? srcVal; // fallback: copy source
        })()
      );
    }
  }

  await Promise.all(jobs);
  return patch;
}
