'use client';

import { useState, useEffect, useCallback, type ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import {
  PlusIcon,
  SearchIcon,
  PencilIcon,
  Trash2Icon,
  EyeIcon,
  ImageIcon,
  Loader2Icon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Wand2Icon,
  SparklesIcon,
  LanguagesIcon,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { useLocale, useTranslations } from 'next-intl';
import { ImageUploader } from '@/components/admin/image-uploader';
import { TagInput } from '@/components/admin/tag-input';
import { CategorySelect } from '@/components/admin/category-select';
import { resolveImageUrl } from '@/lib/s3';
import {
  slugify,
  autoGenerateDescriptions,
  translateGallery,
  autoSlug,
  LANG_LABELS,
  type GalleryLang,
} from '@/lib/gallery-helpers';

const SectionTitle = ({ children }: { children: ReactNode }) => (
  <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/70 -mb-1">
    {children}
  </h3>
);

interface GalleryItem {
  id: string;
  slug: string;
  titleZh: string;
  titleEn: string;
  titleJa: string;
  descriptionZh: string;
  descriptionEn: string;
  descriptionJa: string;
  cosplayer: string;
  character: string;
  series: string;
  cover: string;
  images: string[];
  categories: string[];
  tags: string[];
  rating: string;
  price: number;
  isPremium: boolean;
  downloadUrl: string;
  viewCount: number;
  downloadCount: number;
  createdAt: string;
}

const emptyForm: Partial<GalleryItem> = {
  slug: '',
  titleZh: '', titleEn: '', titleJa: '',
  descriptionZh: '', descriptionEn: '', descriptionJa: '',
  cosplayer: '', character: '', series: '',
  cover: '',
  images: [],
  categories: [],
  tags: [],
  rating: 'sfw',
  price: 0,
  isPremium: false,
  downloadUrl: '',
};

export default function AdminGalleriesPage() {
  const [galleries, setGalleries] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<GalleryItem | null>(null);
  const [form, setForm] = useState<Partial<GalleryItem>>(emptyForm);
  const [saving, setSaving] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [slugTouched, setSlugTouched] = useState(false);
  const [uploadProvider, setUploadProvider] = useState<'s3' | 'imagehost'>('s3');
  const [translating, setTranslating] = useState(false);
  const [slugging, setSlugging] = useState(false);
  const [translateSource, setTranslateSource] = useState<GalleryLang>('zh');
  const router = useRouter();
  const locale = useLocale();
  const t = useTranslations('admin.galleries');
  const tCommon = useTranslations('admin.common');

  const validate = (f: Partial<GalleryItem>): Record<string, string> => {
    const e: Record<string, string> = {};
    if (!f.titleZh?.trim()) e.titleZh = t('errorTitleZh');
    if (!f.slug?.trim()) {
      e.slug = t('errorSlugRequired');
    } else if (!/^[a-z0-9-]+$/.test(f.slug)) {
      e.slug = t('errorSlugFormat');
    }
    if (!f.cover) e.cover = t('errorCover');
    if (!f.images || f.images.length === 0) e.images = t('errorImages');
    return e;
  };

  const fetchGalleries = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: String(page), query });
      const res = await fetch(`/admin/api/galleries?${params}`);
      if (res.status === 401) { router.push(`/${locale}/admin/login`); return; }
      const data = await res.json();
      setGalleries(data.items);
      setTotalPages(data.totalPages);
    } catch (e) {
      console.error('Fetch galleries failed:', e);
    } finally {
      setLoading(false);
    }
  }, [page, query, router]);

  useEffect(() => { fetchGalleries(); }, [fetchGalleries]);

  const openCreate = () => {
    setEditing(null);
    setErrors({});
    setSlugTouched(false);
    setTranslateSource('zh');
    setForm({ ...emptyForm, slug: '' });
    setDialogOpen(true);
  };

  const openEdit = (g: GalleryItem) => {
    setEditing(g);
    setErrors({});
    setSlugTouched(true);
    setTranslateSource(
      g.titleZh ? 'zh' : g.titleEn ? 'en' : g.titleJa ? 'ja' : 'zh'
    );
    setForm({ ...g });
    setDialogOpen(true);
  };

  const handleSave = async () => {
    setSaving(true);
    const e = validate(form);
    setErrors(e);
    if (Object.keys(e).length > 0) {
      setSaving(false);
      return;
    }
    try {
      const method = editing ? 'PUT' : 'POST';
      const body = editing ? { ...form, id: editing.id } : form;
      const res = await fetch('/admin/api/galleries', {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (res.status === 401) { router.push(`/${locale}/admin/login`); return; }
      if (res.ok) {
        setDialogOpen(false);
        fetchGalleries();
      }
    } catch (e) {
      console.error('Save failed:', e);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      const res = await fetch(`/admin/api/galleries?id=${id}`, { method: 'DELETE' });
      if (res.ok) {
        setDeleteConfirm(null);
        fetchGalleries();
      }
    } catch (e) {
      console.error('Delete failed:', e);
    }
  };

  const updateForm = (key: string, value: unknown) => {
    setForm((prev) => ({ ...prev, [key]: value }));
    setErrors((prev) => {
      if (!prev[key]) return prev;
      const next = { ...prev };
      delete next[key];
      return next;
    });
  };

  // Real-time slug follows ONLY the English title box. The Chinese/Japanese
  // boxes must never drive the slug — pinyin/romaji leftovers there would
  // produce junk like "shi-ma". Uses the freshly-typed value `v` (not the
  // stale closure `form`) so it tracks the current keystroke.
  const onTitleChange = (lang: 'Zh' | 'En' | 'Ja', v: string) => {
    updateForm(`title${lang}`, v);
    if (slugTouched || lang !== 'En') return;
    const s = slugify(v);
    if (s) {
      updateForm('slug', s);
      if (errors.slug)
        setErrors((p) => ({ ...p, slug: undefined as unknown as string }));
    }
  };

  // ── Lazy tools ─────────────────────────────
  // One-click slug. If a Latin title exists it's instant; otherwise a CJK
  // title is auto-translated to English (via the free endpoint) and the slug
  // is derived from that English. The English title is also filled in (when
  // empty) so the gallery keeps a proper locale for SEO/OG.
  const handleAutoSlug = async () => {
    setSlugging(true);
    try {
      const res = await autoSlug(form);
      if (!res) {
        setErrors((p) => ({
          ...p,
          slug: t('lazyToolHint'),
        }));
        return;
      }
      updateForm('slug', res.slug);
      setSlugTouched(true);
      if (res.enTitle && !String(form.titleEn || '').trim()) {
        updateForm('titleEn', res.enTitle);
      }
      setErrors((p) => ({ ...p, slug: undefined as unknown as string }));
    } finally {
      setSlugging(false);
    }
  };

  // Build trilingual descriptions from the structured fields.
  const handleAutoDescribe = () => {
    const { descriptionZh, descriptionEn, descriptionJa } = autoGenerateDescriptions({
      cosplayer: form.cosplayer,
      character: form.character,
      series: form.series,
      tags: form.tags,
      imageCount: (form.images || []).length,
    });
    updateForm('descriptionZh', descriptionZh);
    updateForm('descriptionEn', descriptionEn);
    updateForm('descriptionJa', descriptionJa);
    setErrors((prev) => {
      const next = { ...prev };
      delete next.descriptionZh;
      delete next.descriptionEn;
      delete next.descriptionJa;
      return next;
    });
  };

  // Translate title + description from the chosen source language
  // into the other two locales (free MyMemory API, browser-side).
  const handleTranslate = async () => {
    setTranslating(true);
    try {
      const patch = await translateGallery(
        form as Record<string, unknown>,
        translateSource
      );
      Object.entries(patch).forEach(([k, v]) => updateForm(k, v));
    } finally {
      setTranslating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
        <div className="relative flex-1 max-w-sm">
          <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input
            placeholder={t('searchPlaceholder')}
            value={query}
            onChange={(e) => { setQuery(e.target.value); setPage(1); }}
            className="pl-9 bg-white/[0.03] border-white/[0.08]"
            style={{ minHeight: 44 }}
          />
        </div>
        <Button
          onClick={openCreate}
          className="bg-[#ff2d78] hover:bg-[#ff2d78]/90 text-white"
          style={{ boxShadow: '0 0 16px rgba(255,45,120,0.3)' }}
        >
          <PlusIcon className="size-4 mr-2" />
          {t('create')}
        </Button>
      </div>

      {/* Table */}
      <div className="rounded-xl bg-[#262633] border border-white/[0.06] overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/[0.06] bg-white/[0.01]">
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground">{t('colCover')}</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground">{t('colTitle')}</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground hidden md:table-cell">{t('cosplayer')}</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground hidden lg:table-cell">{t('colRating')}</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground hidden lg:table-cell">{t('colPrice')}</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-muted-foreground">{t('colActions')}</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center">
                    <Loader2Icon className="size-6 animate-spin mx-auto text-muted-foreground" />
                  </td>
                </tr>
              ) : galleries.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center text-muted-foreground">
                    <ImageIcon className="size-8 mx-auto mb-2 opacity-40" />
                    {t('noData')}
                  </td>
                </tr>
              ) : (
                galleries.map((g) => (
                  <tr key={g.id} className="border-b border-white/[0.02] hover:bg-white/[0.02] transition-colors">
                    <td className="px-4 py-3">
                      <div className="size-10 rounded-lg bg-[#1c1c28] border border-white/[0.06] overflow-hidden">
                        {g.cover ? (
                          // eslint-disable-next-line @next/next/no-img-element
                          <img
                            src={resolveImageUrl(g.cover)}
                            alt={g.titleZh}
                            className="w-full h-full object-cover"
                            loading="lazy"
                          />
                        ) : (
                          <div className="w-full h-full bg-gradient-to-br from-[#ff2d78]/20 to-[#00d4ff]/20 flex items-center justify-center">
                            <ImageIcon className="size-4 text-muted-foreground" />
                          </div>
                        )}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <p className="text-foreground font-medium truncate max-w-[200px]">{g.titleZh}</p>
                      <p className="text-xs text-muted-foreground">{g.slug}</p>
                    </td>
                    <td className="px-4 py-3 hidden md:table-cell text-muted-foreground">{g.cosplayer}</td>
                    <td className="px-4 py-3 hidden lg:table-cell">
                      <Badge
                        variant="outline"
                        className={cn(
                          'text-xs border',
                          g.rating === 'nsfw'
                            ? 'bg-violet-500/10 text-violet-400 border-violet-500/20'
                            : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                        )}
                      >
                        {g.rating.toUpperCase()}
                      </Badge>
                    </td>
                    <td className="px-4 py-3 hidden lg:table-cell">
                      {g.isPremium && (g.price ?? 0) > 0 ? (
                        <span className="text-[#ff2d78] font-medium">¥{g.price}</span>
                      ) : g.isPremium ? (
                        <span className="text-[#ff2d78] font-medium text-xs px-2 py-0.5 rounded-full bg-[#ff2d78]/10 border border-[#ff2d78]/20">
                          {t('membersOnly')}
                        </span>
                      ) : (
                        <span className="text-emerald-400 font-medium">{t('free')}</span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-1">
                        <button
                          onClick={() => openEdit(g)}
                          className="size-9 flex items-center justify-center rounded-lg text-muted-foreground hover:text-[#00d4ff] hover:bg-[#00d4ff]/10 transition-colors"
                          aria-label={tCommon('edit')}
                        >
                          <PencilIcon className="size-4" />
                        </button>
                        <button
                          onClick={() => setDeleteConfirm(g.id)}
                          className="size-9 flex items-center justify-center rounded-lg text-muted-foreground hover:text-red-400 hover:bg-red-500/10 transition-colors"
                          aria-label={tCommon('delete')}
                        >
                          <Trash2Icon className="size-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-white/[0.06]">
            <span className="text-xs text-muted-foreground">
              {t('page', { page, total: totalPages })}
            </span>
            <div className="flex gap-1">
              <Button
                variant="ghost"
                size="icon"
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
                className="size-8"
              >
                <ChevronLeftIcon className="size-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                disabled={page >= totalPages}
                onClick={() => setPage(page + 1)}
                className="size-8"
              >
                <ChevronRightIcon className="size-4" />
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* Edit/Create Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="bg-[#262633] border-white/[0.08] sm:max-w-6xl w-[calc(100vw-2rem)] max-h-[92vh] overflow-hidden scrollbar-hide">
          <DialogHeader className="shrink-0">
            <DialogTitle className="text-lg" style={{ fontFamily: 'Orbitron, sans-serif' }}>
              {editing ? t('edit') : t('create')}
            </DialogTitle>
          </DialogHeader>

          <div className="flex-1 min-h-0 overflow-y-auto scrollbar-hide space-y-6 py-2 pr-1">
            {/* ── 偷懒工具 ── */}
            <section className="rounded-xl border border-[#ff2d78]/15 bg-[#ff2d78]/[0.03] p-4 space-y-3">
              <div className="flex items-center gap-2 text-sm font-medium text-[#ff2d78]">
                <Wand2Icon className="size-4" />
                {t('lazyToolTitle')}
                <span className="text-xs font-normal text-muted-foreground">
                  {t('lazyToolDesc')}
                </span>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleAutoSlug}
                  disabled={slugging}
                  className="border-[#ff2d78]/30 text-[#ff2d78] hover:bg-[#ff2d78]/10 disabled:opacity-60"
                >
                  {slugging ? (
                    <Loader2Icon className="size-3.5 mr-1.5 animate-spin" />
                  ) : (
                    <SparklesIcon className="size-3.5 mr-1.5" />
                  )}
                  {t('autoSlug')}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleAutoDescribe}
                  className="border-[#ff2d78]/30 text-[#ff2d78] hover:bg-[#ff2d78]/10"
                >
                  <SparklesIcon className="size-3.5 mr-1.5" />
                  {t('autoDesc')}
                </Button>
                <div className="flex items-center gap-2 pl-1">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleTranslate}
                    disabled={translating}
                    className="border-[#00d4ff]/30 text-[#00d4ff] hover:bg-[#00d4ff]/10"
                  >
                    {translating ? (
                      <Loader2Icon className="size-3.5 mr-1.5 animate-spin" />
                    ) : (
                      <LanguagesIcon className="size-3.5 mr-1.5" />
                    )}
                    {t('translateFill')}
                  </Button>
                  <span className="text-xs text-muted-foreground">{t('sourceLang')}</span>
                  <select
                    value={translateSource}
                    onChange={(e) => setTranslateSource(e.target.value as GalleryLang)}
                    className="h-8 rounded-lg bg-white/[0.03] border border-white/[0.08] text-foreground text-xs px-2"
                  >
                    {(['zh', 'en', 'ja'] as GalleryLang[]).map((l) => (
                      <option key={l} value={l}>
                        {LANG_LABELS[l]}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              <p className="text-xs text-muted-foreground/70">
                {t('translateHint')}
              </p>
            </section>

            {/* Section: 基础信息 */}
            <section className="space-y-4">
              <SectionTitle>{t('sectionBasic')}</SectionTitle>

              {/* Slug */}
              <div className="space-y-1.5">
                <Label className="text-xs text-muted-foreground">{t('slugLabel')}</Label>
                <Input
                  value={form.slug || ''}
                  onChange={(e) => {
                    setSlugTouched(true);
                    updateForm('slug', e.target.value);
                  }}
                  className="bg-white/[0.03] border-white/[0.08] font-mono text-sm"
                  style={{ minHeight: 40 }}
                  placeholder={t('slugPlaceholder')}
                />
                {errors.slug && <p className="text-xs text-red-400">{errors.slug}</p>}
              </div>

              {/* Titles */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {errors.titleZh && (
                  <p className="col-span-full text-xs text-red-400">{errors.titleZh}</p>
                )}
                {(['Zh', 'En', 'Ja'] as const).map((lang) => (
                  <div key={lang} className="space-y-1.5">
                    <Label className="text-xs text-muted-foreground">
                      {t('titleLabel')} ({lang === 'Zh' ? '中文' : lang === 'En' ? 'English' : '日本語'})
                    </Label>
                    <Input
                      value={(form as any)[`title${lang}`] || ''}
                      onChange={(e) => onTitleChange(lang, e.target.value)}
                      className="bg-white/[0.03] border-white/[0.08]"
                      style={{ minHeight: 40 }}
                    />
                  </div>
                ))}
              </div>

              {/* Descriptions */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {(['Zh', 'En', 'Ja'] as const).map((lang) => (
                  <div key={lang} className="space-y-1.5">
                    <Label className="text-xs text-muted-foreground">
                      {t('descLabel')} ({lang === 'Zh' ? '中文' : lang === 'En' ? 'English' : '日本語'})
                    </Label>
                    <Textarea
                      value={(form as any)[`description${lang}`] || ''}
                      onChange={(e) => updateForm(`description${lang}`, e.target.value)}
                      className="bg-white/[0.03] border-white/[0.08] min-h-[60px]"
                      rows={2}
                    />
                  </div>
                ))}
              </div>
            </section>

            {/* Section: 关联信息 */}
            <section className="space-y-4">
              <SectionTitle>{t('sectionRelations')}</SectionTitle>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {[
                  { key: 'cosplayer', label: t('cosplayer') },
                  { key: 'character', label: t('character') },
                  { key: 'series', label: t('series') },
                ].map(({ key, label }) => (
                  <div key={key} className="space-y-1.5">
                    <Label className="text-xs text-muted-foreground">{label}</Label>
                    <Input
                      value={(form as any)[key] || ''}
                      onChange={(e) => updateForm(key, e.target.value)}
                      className="bg-white/[0.03] border-white/[0.08]"
                      style={{ minHeight: 40 }}
                    />
                  </div>
                ))}
              </div>
            </section>

            {/* Section: 媒体资源 */}
            <section className="space-y-4">
              <SectionTitle>{t('sectionMedia')}</SectionTitle>
              <div className="flex flex-wrap items-center gap-3">
                <span className="text-xs text-muted-foreground">{t('storageBackend')}</span>
                <div className="inline-flex rounded-lg border border-white/[0.08] overflow-hidden">
                  {(['s3', 'imagehost'] as const).map((p) => (
                    <button
                      key={p}
                      type="button"
                      onClick={() => setUploadProvider(p)}
                      className={cn(
                        'px-3 h-8 text-xs font-medium transition-colors',
                        uploadProvider === p
                          ? 'bg-[#ff2d78] text-white'
                          : 'bg-white/[0.03] text-muted-foreground hover:bg-white/[0.06]'
                      )}
                    >
                      {p === 's3' ? t('storageS3') : t('storageImageHost')}
                    </button>
                  ))}
                </div>
                {uploadProvider === 'imagehost' && (
                  <span className="text-xs text-muted-foreground/70">
                    {form.rating === 'nsfw' ? t('nsfwUploadHint') : t('sfwUploadHint')}
                  </span>
                )}
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <ImageUploader
                    folder={`galleries/${form.slug || 'tmp'}`}
                    value={form.cover || ''}
                    onChange={(v) => updateForm('cover', v)}
                    provider={uploadProvider}
                    nsfw={form.rating === 'nsfw'}
                    label={t('coverLabel')}
                  />
                  {errors.cover && (
                    <p className="text-xs text-red-400">{errors.cover}</p>
                  )}
                </div>
                <div className="space-y-1.5">
                  <ImageUploader
                    folder={`galleries/${form.slug || 'tmp'}`}
                    value={form.images || []}
                    onChange={(v) => updateForm('images', v)}
                    cover={form.cover}
                    onSetCover={(k) => updateForm('cover', k)}
                    multiple
                    provider={uploadProvider}
                    nsfw={form.rating === 'nsfw'}
                    label={t('imagesLabel')}
                  />
                  {errors.images && (
                    <p className="text-xs text-red-400">{errors.images}</p>
                  )}
                </div>
              </div>
            </section>

            {/* Section: 分类 & 标签 */}
            <section className="space-y-4">
              <SectionTitle>{t('sectionTaxonomy')}</SectionTitle>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs text-muted-foreground">
                    {t('categoryHint')}
                  </Label>
                  <CategorySelect
                    value={form.categories || []}
                    onChange={(slugs) => updateForm('categories', slugs)}
                  />
                </div>
                <TagInput
                  label={t('tagsLabel')}
                  value={form.tags || []}
                  onChange={(tags) => updateForm('tags', tags)}
                  placeholder={t('tagsPlaceholder')}
                />
              </div>
            </section>

            {/* Section: 发布设置 */}
            <section className="space-y-4">
              <SectionTitle>{t('sectionPublish')}</SectionTitle>
              <div className="grid grid-cols-3 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs text-muted-foreground">{t('ratingLabel')}</Label>
                  <select
                    value={form.rating || 'sfw'}
                    onChange={(e) => updateForm('rating', e.target.value)}
                    className="w-full h-10 rounded-lg bg-white/[0.03] border border-white/[0.08] text-foreground text-sm px-3"
                  >
                    <option value="sfw">{t('ratingSfw')}</option>
                    <option value="nsfw">{t('ratingNsfw')}</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs text-muted-foreground">{t('priceLabel')}</Label>
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={form.price || 0}
                    onChange={(e) => updateForm('price', parseFloat(e.target.value) || 0)}
                    className="bg-white/[0.03] border-white/[0.08]"
                    style={{ minHeight: 40 }}
                  />
                  {errors.price && <p className="text-xs text-red-400">{errors.price}</p>}
                  {form.isPremium && (form.price ?? 0) > 0 && (
                    <p className="text-xs text-muted-foreground/70">
                      {t('pricePaidHint', { price: (form.price ?? 0).toFixed(2) })}
                    </p>
                  )}
                  {form.isPremium && (form.price ?? 0) <= 0 && (
                    <p className="text-xs text-muted-foreground/70">
                      {t('priceFreeHint')}
                    </p>
                  )}
                </div>
                <div className="space-y-1.5 flex items-end pb-1">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={form.isPremium || false}
                      onChange={(e) => updateForm('isPremium', e.target.checked)}
                      className="size-4 rounded accent-[#ff2d78]"
                    />
                    <span className="text-xs text-muted-foreground">{t('membersOnlyLabel')}</span>
                  </label>
                </div>
              </div>

              {/* 外链下载地址（网盘/外部链接，可选） */}
              <div className="space-y-1.5">
                <Label className="text-xs text-muted-foreground">
                  {t('externalDownloadLabel')}
                </Label>
                <Input
                  value={form.downloadUrl || ''}
                  onChange={(e) => updateForm('downloadUrl', e.target.value)}
                  placeholder={t('externalDownloadPlaceholder')}
                  className="bg-white/[0.03] border-white/[0.08]"
                  style={{ minHeight: 40 }}
                />
                <p className="text-xs text-muted-foreground/70">
                  {t('externalDownloadHint')}
                </p>
              </div>
            </section>
          </div>

          {/* Actions (sticky footer, outside scroll region) */}
          <div className="shrink-0 flex justify-end gap-3 pt-3 border-t border-white/[0.06]">
            <Button variant="ghost" onClick={() => setDialogOpen(false)} className="text-muted-foreground">
              {t('cancel')}
            </Button>
            <Button
              onClick={handleSave}
              disabled={saving}
              className="bg-[#ff2d78] hover:bg-[#ff2d78]/90 text-white"
              style={{ boxShadow: '0 0 16px rgba(255,45,120,0.3)' }}
            >
              {saving ? (
                <Loader2Icon className="size-4 animate-spin mr-2" />
              ) : null}
              {editing ? t('save') : t('createGallery')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <Dialog open={!!deleteConfirm} onOpenChange={() => setDeleteConfirm(null)}>
        <DialogContent className="bg-[#262633] border-white/[0.08] max-w-sm">
          <DialogHeader>
            <DialogTitle className="text-lg">{t('deleteTitle')}</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {t('deleteDesc')}
          </p>
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="ghost" onClick={() => setDeleteConfirm(null)} className="text-muted-foreground">
              {t('cancelDelete')}
            </Button>
            <Button
              onClick={() => deleteConfirm && handleDelete(deleteConfirm)}
              className="bg-red-500 hover:bg-red-600 text-white"
            >
              {t('confirmDelete')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
